export const cardData = [
  {
    title: "Basic",
    titleColor: "text-[#FFFFDD]",
    bgColor: "bg-[#186F65]",
    btnBgColor: "bg-emerald-500",
    caption: "Perfect for Small Business",
    captionColor: "text-[#B5CB99]",
    bonusCaption: "",
    list: [
      "Upto 5 pages",
      "Custom WebDesign",
      "Contact Form",
      "Mobile Responsive",
      "Google Reviews",
    ],
    price: "For A$1699",
  },
  {
    title: "Premium",
    caption: "Recommended",
    bonusCaption: "",
    titleColor: "text-[#FFF0CE]",
    bgColor: "bg-[#0C356A]",
    btnBgColor: "bg-[#0174BE]",
    captionColor: "text-[#FFC436]",
    list: [
      "Upto 15 pages",
      "Custom WebDesign",
      "Contact Form",
      "Mobile Responsive",
      "Google Reviews",
      "Dark mode",
    ],
    price: "For A$2699",
  },
  {
    title: "Custom",
    caption: "Built with your preferences",
    bonusCaption: "Starting from A$1499",
    titleColor: "text-[#ECF4D6]",
    bgColor: "bg-[#265073]",
    btnBgColor: "bg-[#265073]",
    captionColor: "text-[#9AD0C2]",
    list: [
      "Unlimited pages",
      "Custom WebDesign",
      "Contact Form",
      "Mobile Responsive",
      "Google Reviews",
      "Dark mode",
      "Animation Effects",
      "Transition Effects",
    ],
    price: "Build Now",
  },
];
