export const cardData = [
  {
    title: "Basic",
    titleColor: "text-green-900",
    bgColor: "bg-green-100",
    btnBgColor: "bg-green-300",
    caption: "Perfect for Small Business",
    bonusCaption: "",
    list: [
      "Upto 5 pages",
      "Custom WebDesign",
      "Contact Form",
      "Mobile Responsive",
      "Google Reviews",
      "Dark mode",
    ],
    price: "Purchase for A$1699",
  },
  {
    title: "Premium",
    caption: "Recommended",
    bonusCaption: "",
    titleColor: "text-pink-900",
    bgColor: "bg-pink-100",
    btnBgColor: "bg-pink-300",

    list: [
      "Upto 15 pages",
      "Custom WebDesign",
      "Contact Form",
      "Mobile Responsive",
      "Google Reviews",
      "Dark mode",
    ],
    price: "Purchase for A$2699",
  },
  {
    title: "Custom",
    caption: "Built with your preferences",
    bonusCaption: "Starting from A$1499",
    titleColor: "text-blue-900",
    bgColor: "bg-blue-100",
    btnBgColor: "bg-blue-300",

    list: [
      "Unlimited pages",
      "Custom WebDesign",
      "Contact Form",
      "Mobile Responsive",
      "Google Reviews",
      "Dark mode",
      "Animation Effects",
      "Transition Effects",
    ],
    price: "Build Now",
  },
];
